scan_filter_chain:
- name: polygon_filter
  type: laser_filters/LaserScanPolygonFilter
  params:
    polygon_frame: map
    polygon: [[-2.426, 0.249], [0.496, 0.493], [0.489, 1.516], [-1.965, 1.347]]
    invert: true
