scan_filter_chain:
- name: polygon_filter
  type: laser_filters/LaserScanPolygonFilter
  params:
    polygon_frame: map
    polygon: [[-2.426, 0.249], [0.496, 0.493], [0.572, -0.621], [-1.921, -0.643]]
    invert: true
