scan_filter_chain:
- name: box_filter
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: map
    max_x: 0.3
    max_y: 0.3
    max_z: 2.0
    min_x: -3.0
    min_y: -0.5
    min_z: -0.28
    invert: true
