scan_filter_chain:
- name: polygon_filter
  type: laser_filters/LaserScanPolygonFilter
  params:
    polygon_frame: map
    polygon: [[-38.082, -7.981], [-38.134, -7.180], [-37.46, -7.187], [-37.338, -7.917]]
    invert: true
# -37.838 -7.600