scan_filter_chain:
- name: polygon_filter
  type: laser_filters/LaserScanPolygonFilter
  params:
    polygon_frame: map
    polygon: [[-26.593, -4.109], [-26.511, -5.065], [-25.853, -4.840], [-25.914, -3.845]]
    invert: true
