scan_filter_chain:
- name: box_filter
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: scan_top
    max_x: -0.98197 #the x dist of top lidar and back lidar
    max_y: 0.4
    max_z: 0.1
    min_x: -1.28197 #change it
    min_y: -0.4
    min_z: -0.1
    invert: true