scan_filter_chain:
- name: box_filter
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: livox_frame_192_168_1_104
    max_x: 2.0
    max_y: 0.3
    max_z: 0.1
    min_x: 0.5
    min_y: -0.3
    min_z: -0.1
    invert: true