scan_filter_chain:
- name: polygon_filter
  type: laser_filters/LaserScanPolygonFilter
  params:
    polygon_frame: map
    # polygon: [[-3.829, -6.854], [-3.880, -7.828], [-2.910, -7.756], [-3.016, -6.772]]
    polygon: [[-3.688, -6.639], [-3.688, -7.739], [-3.288, -7.739], [-3.288, -6.639]]
    invert: true
