scan_filter_chain:
- name: polygon_filter
  type: laser_filters/LaserScanPolygonFilter 
  params:
    polygon_frame: map
    # polygon: [[-8.57, -8.6], [-8.56, -8.0], [-9.73, -8.0], [-9.73, -8.6]]
    polygon: [[, ], [-8.56, -8.0], [-9.73, -8.0], [-9.73, -8.6]]
    invert: true

#dirty_unload_backward = [-99.57, 0.55, 0.9981, -0.0607]
#dirty_unload_2 = [-98.24, 0.69, 0.9971, -0.0763]
#dirty_unload_1 = [-96.92, 0.86, 0.9985, -0.0543]
